function Y = RegressoreRR(q, qdot, qrddot)
  
    q1 = q(1);     q2 = q(2);
    q1dot = qdot(1); q2dot = qdot(2);
    q1dd_r = qrddot(1); q2dd_r = qrddot(2);

    c2 = cos(q2);
    s2 = sin(q2);

    % Regressore Y (2x6)
    Y = [
        q1dd_r, ...
        q1dd_r*c2 + q2dd_r - q2dot*s2*q1dot, ...
        q2dd_r*c2 - q2dot*s2*q1dot, ...
        0, ...
        cos(q1), ...
        cos(q1 + q2);
        %
        0, ...
        q1dd_r, ...
        q1dd_r*c2 + q1dot*s2*q2dot, ...
        q2dd_r, ...
        0, ...
        cos(q1 + q2)
    ];
end
